### ISSUE TITLE
git url

### ISSUE THREAD

**Issue by naychrist** [ryanbartley/Cinder-Bullet3D#5]
hey there,
thanks for the block! any chance of adding the following attribute to the block tag in the cinderblock file so that we can add it as a submodule with tinderbox?

`git="https://github.com/ryanbartley/Cinder-Bullet3D.git"`

**Comment by ryanbartley** [comment]
Sure. I don't have it in front of me right now. If you'd like to push the change I'll merge it. Otherwise, I can do it tomorrow.

**Comment by ryanbartley** [comment]
This should be fixed now. Sorry it took so long. Closing.
