### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Dazzid** [ryanbartley/Cinder-Bullet3D#6]
Hi!
I have an error, maybe because I need to install bullet library first? It doesn't come with the block?
Error:
    clang: error: no such file or directory: '../../../lib/macosx/libBulletCollision_x64_debug.a'
    clang: error: no such file or directory: '../../../lib/macosx/libBulletDynamics_x64_debug.a'
    clang: error: no such file or directory: '../../../lib/macosx/libBulletSoftBody_x64_debug.a'
    clang: error: no such file or directory: '../../../lib/macosx/libLinearMath_x64_debug.a'

**Comment by ryanbartley** [comment]
Hi, you should be able to run the Install.sh in the root directory and it will download the needed libs.

**Comment by Dazzid** [comment]
Amazing! thanks

**Comment by ryanbartley** [comment]
No problem. Let me know if you have any other problems.
