### ISSUE TITLE
Setting gravity

### ISSUE THREAD

**Issue by Dazzid** [ryanbartley/Cinder-Bullet3D#7]
Hello, 
One question, in SphereGravity how easy is to setup gravity? 
I'm trying this:
btBroadphaseInterface\* broadphase = new btDbvtBroadphase();
btDefaultCollisionConfiguration\* collisionConfiguration = new btDefaultCollisionConfiguration();
btCollisionDispatcher\* dispatcher = new btCollisionDispatcher(collisionConfiguration);
btSequentialImpulseConstraintSolver\* solver = new btSequentialImpulseConstraintSolver;
btDiscreteDynamicsWorld\* dynamicsWorld = new            btDiscreteDynamicsWorld(dispatcher,broadphase,solver,collisionConfiguration);
dynamicsWorld->setGravity(btVector3(0,-10,0));

but it doesn't really affect the spheres. 
Thanks for the help

**Comment by Dazzid** [comment]
Ah I already found it :)

**Comment by ryanbartley** [comment]
Sorry it took so long to get back to this. I'm happy you found it and I'm going to close the issue. Please feel free to report any other weirdness that happens.
